GET https://api.odcloud.kr/api/15109950/v1/uddi:1f78fe49-78b4-4784-a5f0-e2c8a60515b4?page=1&perPage=1&serviceKey=OFbtvXMtuBc6t%2F3DYGVvVAtFtWdYiMZq8LCaFMLjOYvQ4Hk5knFcCyJmFKKkTk74J7K6O57MKYIIb8oL%2FOgihw%3D%3D